Settings:
  debug: true
  bossTargetRange: 50.0
  defaultNearbyRadius: 250.0
  nearbyFormat: '{name} ({distance}m)'

  BlockedWorlds:
    enabled: false
    worlds:
    - 'world_the_end'
    - 'world_nether'
Toggles:
  bossShop: true
  endermanTeleporting: true
  potionsAffectingBoss: true
Limits:
  maxNearbyRadius: 500.0
Hooks:
  ASkyBlock:
    enabled: false
    onOwnIsland: false
  Factions:
    enabled: false
    useWarzoneSpawnRegion: false
  StackMob:
    enabled: false
  WorldGuard:
    enabled: true
    spawnRegions:
    - 'spawn_region1'
    - 'spawn_region2'
    blockedRegions:
    - 'blocked_region1'
    - 'blocked_region2'
Display:
  BossListEditor:
    name: '&3{position} Entity'
    lore:
    - '&3Left Click &8»'
    - '&7Edit the {targetType} for this'
    - '&7entity in the section.'
    - '&7'
    - '&3Right Click &8»'
    - '&7Remove this section, can be done'
    - '&7to anything above the first one.'
  EquipmentEditor:
    name: '{name} &a&l** Selected **'
  EditDrops:
    lore:
    - '&3Type: &7{type}'
    - '&7'
    - '&7Click here to select this drop'
    - '&7table as the current one.'
  AutoSpawns:
    menuName: '&b&lEpicBosses &3&lAutoSpawns'
  Bosses:
    menuName: '&b&lEpicBosses &3&lBosses'
    name: '&b&l{name}'
    lore:
    - '&3Editing: &f{enabled}'
    - '&7'
    - '&3Left Click »'
    - '&7Get spawn item for custom'
    - '&7boss.'
    - '&7'
    - '&3Right Click »'
    - '&7Edit the custom boss.'
  DropTable:
    menuName: '&b&lEpicBosses &3&lDropTables'
    name: '&b&l{name} Drop Table'
    lore:
    - '&3Type: &7{type}'
    - '&7'
    - '&7Click to edit the drop table.'
  Items:
    menuName: '&b&lEpicBosses &3&lCustom Items'
  Shop:
    menuName: '&b&lEpicBosses &3&lShop'
    name: '&b&lBuy {name}''s Egg'
    lore:
    - '&3Cost: &a$&f{price}'
  Skills:
    menuName: '&b&lEpicBosses &3&lSkills'
    name: '&b&l{name} Skill'
    lore:
    - '&3Type: &7{type}'
    - '&3Display Name: &7{displayName}'
    - '&3Custom Message: &7{customMessage}'
    - '&3Radius: &7{radius}'
    - '&7'
    - '&7Click to edit the custom skill.'