Settings:
  debug: false
  bossTargetRange: 50.0

  BlockedWorlds:
    enabled: false
    worlds:
    - 'world_the_end'
    - 'world_nether'
Toggles:
  endermanTeleporting: true
  potionsAffectingBoss: true
Hooks:
  ASkyBlock:
    enabled: false
    onOwnIsland: false
  Factions:
    enabled: false
    useWarzoneSpawnRegion: false
  StackMob:
    enabled: false
  WorldGuard:
    enabled: true
    spawnRegions:
    - 'spawn_region1'
    - 'spawn_region2'
    blockedRegions:
    - 'blocked_region1'
    - 'blocked_region2'
Display:
  Bosses:
    name: '&e&l{name}'
    lore:
    - '&eEnabled: &7{enabled}'
    - '&7'
    - '&eLeft Click »'
    - '&7Edit the custom boss.'
    - '&7'
    - '&eRight Click »'
    - '&7Get spawn item for custom'
    - '&7boss.'