Settings:
  debug: false
  bossTargetRange: 50.0
  defaultNearbyRadius: 250.0
  nearbyFormat: '{name} ({distance}m)'

  BlockedWorlds:
    enabled: false
    worlds:
    - 'world_the_end'
    - 'world_nether'
Toggles:
  bossShop: true
  endermanTeleporting: true
  potionsAffectingBoss: true
Limits:
  maxNearbyRadius: 500.0
Hooks:
  ASkyBlock:
    enabled: false
    onOwnIsland: false
  Factions:
    enabled: false
    useWarzoneSpawnRegion: false
  StackMob:
    enabled: false
  WorldGuard:
    enabled: true
    spawnRegions:
    - 'spawn_region1'
    - 'spawn_region2'
    blockedRegions:
    - 'blocked_region1'
    - 'blocked_region2'
Display:
  AutoSpawns:
    menuName: '&b&lEpicBosses &3&lAutoSpawns'
  Bosses:
    menuName: '&b&lEpicBosses &3&lItems'
    name: '&b&l{name}'
    lore:
    - '&3Editing: &f{enabled}'
    - '&7'
    - '&3Left Click »'
    - '&7Get spawn item for custom'
    - '&7boss.'
    - '&7'
    - '&3Right Click »'
    - '&7Edit the custom boss.'
  DropTable:
    menuName: '&b&lEpicBosses &3&lDropTables'
  Items:
    menuName: '&b&lEpicBosses &3&lCustom Items'
  Shop:
    menuName: '&b&lEpicBosses &3&lShop'
    name: '&b&lBuy {name}''s Egg'
    lore:
    - '&3Cost: &a$&f{price}'
  Skills:
    menuName: '&b&lEpicBosses &3&lSkills'