name: ${plugin.name}
main: ${plugin.main}
version: ${plugin.version}
author: ${plugin.author}
api-version: 1.13
softdepend: [PlaceholderAPI, PlayerPoints, Vault] # TODO: Add other softdepends
commands:
  Boss:
    description: Used to handle all CustomBosses related commands.
    default: true
    aliases: [bosses, eb, epicbosses]